spring:
  datasource:
    #url: jdbc:mysql://localhost/workflow_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/workflow_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
security:
  basic:
    enabled: false

